class GlobalState {
    constructor() {
        this.sectorFlow = {};
        this.marketRegime = "SIDEWAYS";
        this.volatilityIndex = 15;
        this.SECTOR_MAP = {
            HDFCBANK: "BANKING", ICICIBANK: "BANKING", KOTAKBANK: "BANKING", AXISBANK: "BANKING", SBIN: "BANKING", INDUSINDBK: "BANKING", PNB: "BANKING", FEDERALBNK: "BANKING", IDFCFIRSTB: "BANKING", BANKBARODA: "BANKING", AUBANK: "BANKING", BANDHANBNK: "BANKING",
            TCS: "IT", INFY: "IT", HCLTECH: "IT", WIPRO: "IT", LTIM: "IT", TECHM: "IT", COFORGE: "IT", PERSISTENT: "IT", MPHASIS: "IT", LTTS: "IT",
            RELIANCE: "ENERGY", ONGC: "ENERGY", BPCL: "ENERGY", IOC: "ENERGY", COALINDIA: "ENERGY", GAIL: "ENERGY", NTPC: "ENERGY", POWERGRID: "ENERGY", ADANIGREEN: "ENERGY", ADANITRANS: "ENERGY",
            JSWSTEEL: "METALS", HINDALCO: "METALS", VEDL: "METALS", TATASTEEL: "METALS", NMDC: "METALS", SAIL: "METALS", NATIONALUM: "METALS",
            HINDUNILVR: "FMCG", ITC: "FMCG", NESTLEIND: "FMCG", BRITANNIA: "FMCG", VBL: "FMCG", GODREJCP: "FMCG", DABUR: "FMCG", MARICO: "FMCG", TATACONSUM: "FMCG",
            MARUTI: "AUTO", TATAMOTORS: "AUTO", "M&M": "AUTO", "BAJAJ-AUTO": "AUTO", BAJAJ_AUTO: "AUTO", HEROMOTOCO: "AUTO", EICHERMOT: "AUTO", TVSMOTOR: "AUTO", ASHOKLEY: "AUTO", BHARATFORG: "AUTO",
            BHARTIARTL: "TELECOM", IDEA: "TELECOM", INDUSTOWER: "TELECOM",
            SUNPHARMA: "PHARMA", DRREDDY: "PHARMA", REDDY: "PHARMA", CIPLA: "PHARMA", DIVISLAB: "PHARMA", APOLLOHOSP: "PHARMA", AUROPHARMA: "PHARMA", LUPIN: "PHARMA", BIOCON: "PHARMA", TORNTPHARM: "PHARMA",
            LT: "INFRA", ADANIPORTS: "INFRA", ADANIENT: "INFRA", ULTRACEMCO: "INFRA", GRASIM: "INFRA", AMBUJACEM: "INFRA", ACC: "INFRA",
            BAJFINANCE: "FINANCE", BAJAJFINSV: "FINANCE", CHOLAFIN: "FINANCE", RECLTD: "FINANCE", PFC: "FINANCE", SHRIRAMFIN: "FINANCE", MUTHOOTFIN: "FINANCE", SBILIFE: "FINANCE", HDFCLIFE: "FINANCE",
            ASIANPAINT: "CONSUMER", TITAN: "CONSUMER", BERGEPAINT: "CONSUMER", PIDILITIND: "CONSUMER", TRENT: "CONSUMER",
            HAL: "DEFENSE", BEL: "DEFENSE", BDL: "DEFENSE", MAZDOCK: "DEFENSE",
            NSEI: "INDEX", NSEBANK: "INDEX", BSESN: "INDEX", GSPC: "INDEX", IXIC: "INDEX",
            VIX: "MACRO", INDIAVIX: "MACRO"
        };
    }
}

module.exports = new GlobalState();
