/**
 * 🔱 PROMETHEUS — RESEARCH SNAPSHOT GENERATOR
 * PHASE: RESEARCH INTELLIGENCE
 * 
 * Generates automated daily, weekly, and monthly research audit reports
 * summarizing survivability and validation metrics.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const AUDIT_DIR = path.join(__dirname, '../data/research/audits');

class ResearchSnapshotGenerator {
    constructor() {
        if (!fs.existsSync(AUDIT_DIR)) fs.mkdirSync(AUDIT_DIR, { recursive: true });
    }

    generate(verdictData, survivabilityData, coreMetrics) {
        const timestamp = new Date().toISOString().split('T')[0];
        const filename = path.join(AUDIT_DIR, `RESEARCH_AUDIT_${timestamp}.md`);

        const content = `# PROMETHEUS RESEARCH AUDIT — ${timestamp}

## 1. CAMPAIGN VERDICT
* **Deployment Tier:** ${verdictData.verdict}
* **Readiness Score:** ${verdictData.score}/100

## 2. CORE SURVIVABILITY
* **Total Trades:** ${coreMetrics.totalTrades}
* **Edge Trend:** ${survivabilityData.trendDirection}
* **Lifetime Expectancy:** ₹${survivabilityData.lifetime?.expectancy?.toFixed(2) || 0}
* **L50 Profit Factor:** ${survivabilityData.rolling50?.profitFactor?.toFixed(2) || 0}

## 3. STRUCTURAL PENALTIES
${verdictData.penalties && verdictData.penalties.length > 0 ? verdictData.penalties.map(p => `- [FAIL] ${p}`).join('\n') : '- None detected. Clean edge.'}

*Auto-generated by Prometheus Research Intelligence*
`;

        try {
            fs.writeFileSync(filename, content);
            return filename;
        } catch (e) {
            console.error('[SNAPSHOT] Failed to write audit:', e.message);
            return null;
        }
    }
}

module.exports = new ResearchSnapshotGenerator();
