'use strict';

const fs = require('fs');
const path = require('path');

const SNAPSHOT_DIR = path.join(__dirname, '../data/research_snapshots');

/**
 * 🔱 PROMETHEUS — DAILY RESEARCH SNAPSHOT GENERATOR V4
 * PHASE: STATISTICAL DISCIPLINE & OVERFITTING DEFENSE
 */
function generateDailySnapshot(analytics, decayStatus) {
    const today = new Date().toISOString().split('T')[0];
    const { 
        meta, expectancy, durability, execution, calibration, failures, 
        sampleQuality, outliers, walkForward, diversity, consistency, verdict 
    } = analytics || {};

    const snapshot = {
        snapshotDate: today,
        generatedAt: new Date().toISOString(),
        version: 4,
        verdict,
        
        defenseMetrics: {
            sampleQualityScore: sampleQuality?.score || 0,
            sampleQualityStatus: sampleQuality?.status || 'UNKNOWN',
            outlierDominated: outliers?.isOutlierDominated || false,
            walkForwardStatus: walkForward?.status || 'UNKNOWN',
            edgeDiversityScore: diversity?.score || 0,
            equityConsistencyStatus: consistency?.status || 'UNKNOWN'
        },

        performance: {
            totalTrades: meta?.tradeCount || 0,
            expectancy: expectancy?.expectancyPerTrade || 0,
            alphaRetention: execution?.alphaRetentionPct || 0,
            winRate: expectancy?.winRate || 0,
            profitFactor: expectancy?.profitFactor || 0
        },

        statisticalValidation: {
            trimmedExpectancy: outliers?.trimmedExpectancy || 0,
            oosExpectancy: walkForward?.outOfSample?.expectancyPerTrade || 0,
            oosDegradation: walkForward?.degradationPct || 0,
            sharpeProxy: consistency?.sharpeProxy || 0,
            profitableRegimes: diversity?.profitableRegimeCount || 0
        }
    };

    // 1. Persist JSON Report
    try {
        fs.mkdirSync(SNAPSHOT_DIR, { recursive: true });
        fs.writeFileSync(path.join(SNAPSHOT_DIR, `${today}_REPORT_V4.json`), JSON.stringify(snapshot, null, 2));
    } catch (e) {
        console.error('[SNAPSHOT] JSON Persist failed:', e.message);
    }

    // 2. Generate Markdown Summary (DAILY_EDGE_SUMMARY.md)
    try {
        const md = generateMarkdownSummary(snapshot);
        fs.writeFileSync(path.join(SNAPSHOT_DIR, `${today}_SUMMARY.md`), md);
    } catch (e) {
        console.error('[SNAPSHOT] MD Persist failed:', e.message);
    }

    // 3. Generate Weekly Audit if it's the end of the week (or just generate it daily for the campaign)
    try {
        const auditMd = generateWeeklyAudit(snapshot);
        fs.writeFileSync(path.join(SNAPSHOT_DIR, `${today}_WEEKLY_AUDIT.md`), auditMd);
    } catch (e) {
        console.error('[SNAPSHOT] Weekly Audit Persist failed:', e.message);
    }

    return snapshot;
}

function generateWeeklyAudit(s) {
    const d = s.defenseMetrics;
    const sv = s.statisticalValidation;
    const p = s.performance;
    
    // Status helpers
    const checkExp = p.expectancy > 0 ? 'PASS' : 'FAIL';
    const checkPF = p.profitFactor > 1.2 ? 'PASS' : p.profitFactor > 1 ? 'WARNING' : 'FAIL';
    const checkOOS = sv.oosDegradation < 30 ? 'PASS' : sv.oosDegradation < 50 ? 'WARNING' : 'FAIL';
    const checkAlpha = p.alphaRetention > 50 ? 'PASS' : p.alphaRetention > 30 ? 'WARNING' : 'FAIL';
    const checkOutlier = d.outlierDominated ? 'FAIL' : 'PASS';
    
    return `# 🔱 PROMETHEUS WEEKLY RESEARCH AUDIT
Date: ${s.snapshotDate}

## 📊 EDGE EVOLUTION TRACKING
| Metric | Value | Status |
|---|---|---|
| Net Expectancy | ₹${p.expectancy.toFixed(2)} | **${checkExp}** |
| Profit Factor | ${p.profitFactor} | **${checkPF}** |
| Alpha Retention | ${p.alphaRetention}% | **${checkAlpha}** |

## 🛡️ ROBUSTNESS & DEPLOYMENT
| Category | Value | Status |
|---|---|---|
| Outlier Dependence | ${d.outlierDominated ? 'Yes' : 'No'} | **${checkOutlier}** |
| Walk-Forward Robustness | ${d.walkForwardStatus} | **${checkOOS}** |
| Regime Diversity Score | ${d.edgeDiversityScore}/100 | **${d.edgeDiversityScore > 60 ? 'PASS' : 'WARNING'}** |
| Sample Quality | ${d.sampleQualityScore}/100 | **${d.sampleQualityScore > 70 ? 'PASS' : 'WARNING'}** |

**Deployment Verdict**: ${s.verdict}

---
*Generated by Prometheus Research Campaign Operations*
`;
}

function generateMarkdownSummary(s) {
    const d = s.defenseMetrics;
    const sv = s.statisticalValidation;
    const p = s.performance;

    return `# 🔱 PROMETHEUS STATISTICAL DEFENSE SUMMARY // ${s.snapshotDate}
    
## 🛡️ OVERFITTING DEFENSE
- **Verdict**: \`${s.verdict}\`
- **Sample Quality Score**: ${d.sampleQualityScore} / 100 (\`${d.sampleQualityStatus}\`)
- **Outlier Dominated**: ${d.outlierDominated ? '🔴 YES (FRAGILE)' : '🟢 NO (ROBUST)'}
- **Walk-Forward Status**: \`${d.walkForwardStatus}\`
- **Edge Diversity Score**: ${d.edgeDiversityScore} / 100

## 📈 STATISTICAL ROBUSTNESS
- **Trimmed Expectancy**: ₹${sv.trimmedExpectancy.toFixed(2)} (Removing outliers)
- **OOS Performance**: ₹${sv.oosExpectancy.toFixed(2)} (${sv.oosDegradation}% degradation)
- **Sharpe Proxy**: ${sv.sharpeProxy.toFixed(4)}
- **Regime Breadth**: ${sv.profitableRegimes} profitable regimes

## 📊 PERFORMANCE SUMMARY
- **Total Trades**: ${p.totalTrades}
- **Net Expectancy**: ₹${p.expectancy.toFixed(2)}
- **Win Rate**: ${p.winRate}%
- **Profit Factor**: ${p.profitFactor}

---
_Generated by Prometheus Statistical Discipline Engine_
`;
}

module.exports = { generateDailySnapshot, generateWeeklyAudit };
