const { EVENT_TYPES } = require('../engine/executionLedger');

/**
 * 🔱 PROMETHEUS — INTEGRITY TRANSITION RULES
 * Explicit rules for what constitutes a valid causal lineage.
 */

// A child event MUST have one of these parents.
const CAUSAL_REQUIREMENTS = {
    [EVENT_TYPES.SIGNAL_GENERATED]: [EVENT_TYPES.TICK_RECEIVED],
    [EVENT_TYPES.RISK_APPROVED]: [EVENT_TYPES.SIGNAL_GENERATED],
    [EVENT_TYPES.RISK_REJECTED]: [EVENT_TYPES.SIGNAL_GENERATED],
    [EVENT_TYPES.ALLOCATION_CREATED]: [EVENT_TYPES.RISK_APPROVED],
    [EVENT_TYPES.EXECUTION_REQUESTED]: [EVENT_TYPES.ALLOCATION_CREATED],
    [EVENT_TYPES.SIM_FILL_RECEIVED]: [EVENT_TYPES.EXECUTION_REQUESTED],
    [EVENT_TYPES.EXECUTION_SKIPPED]: [EVENT_TYPES.RISK_APPROVED, EVENT_TYPES.SIGNAL_GENERATED],
    [EVENT_TYPES.POSITION_CLOSED]: [EVENT_TYPES.SIM_FILL_RECEIVED]
};

// Events that should NEVER appear more than once per traceId
// (Note: POSITION_CLOSED removed from this list because partial closes exist)
const EXACTLY_ONCE_EVENTS = [
    EVENT_TYPES.SIGNAL_GENERATED,
    EVENT_TYPES.RISK_APPROVED,
    EVENT_TYPES.RISK_REJECTED,
    EVENT_TYPES.ALLOCATION_CREATED,
    EVENT_TYPES.EXECUTION_REQUESTED,
    EVENT_TYPES.SIM_FILL_RECEIVED
];

module.exports = {
    CAUSAL_REQUIREMENTS,
    EXACTLY_ONCE_EVENTS
};
